# Generated by Django 5.1.4 on 2025-01-14 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('startup', 'Startup'), ('freelancer', 'Freelancer'), ('incubator', 'Incubator'), ('accelerator', 'Accelerator'), ('investor', 'Investor'), ('project_holder', 'Project Holder')], default='user', max_length=20),
        ),
    ]
