# Generated by Django 5.1.4 on 2025-02-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('startup', 'Startup'), ('freelancer', 'Freelancer'), ('incubator', 'Incubator'), ('accelerator', 'Accelerator'), ('investor', 'Investor'), ('project_holder', 'Project Holder')], max_length=20, null=True),
        ),
    ]
