# Generated by Django 5.1.4 on 2025-02-01 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='pending_role',
            field=models.CharField(blank=True, choices=[('user', 'User'), ('startup', 'Startup'), ('freelancer', 'Freelancer'), ('incubator', 'Incubator'), ('accelerator', 'Accelerator'), ('investor', 'Investor'), ('project_holder', 'Project Holder')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
