# Generated by Django 5.1.4 on 2025-02-01 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_profile_is_verified_profile_pending_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='accelerator_certificate',
            field=models.FileField(blank=True, null=True, upload_to='accelerator_certificates/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='accelerator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='accelerator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='business_license',
            field=models.FileField(blank=True, null=True, upload_to='business_licenses/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='incubator_certificate',
            field=models.FileField(blank=True, null=True, upload_to='incubator_certificates/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='incubator_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='incubator_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='investment_focus',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='investment_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='investor_certificate',
            field=models.FileField(blank=True, null=True, upload_to='investor_certificates/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='portfolio_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='project_proposal',
            field=models.FileField(blank=True, null=True, upload_to='project_proposals/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='resume',
            field=models.FileField(blank=True, null=True, upload_to='resumes/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='skills',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
