# Generated by Django 5.1.4 on 2025-02-01 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rolerequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolerequest',
            name='role_specific_data',
            field=models.JSONField(default=dict),
        ),
    ]
