# Generated by Django 5.1.4 on 2025-02-01 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rolerequest_role_specific_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolerequest',
            name='role_specific_data',
            field=models.FileField(upload_to=''),
        ),
    ]
